[package]
name = "rust_canonical_numbering"
version = "0.1.0"
authors = ["Qin Wan <rogerwq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
purr = "0.9"