[package]
name = "graph_canonicalization"
version = "0.1.0"
authors = ["Qin Wan <rogerwq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
purr = "0.9"
chem = "0.0.2"

[dev-dependencies]
rand = "0.8.4"